# .github/workflows/development.yml
name: Build and Deploy to Netlify
on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
jobs:
  run tests:
    runs-on: ubuntu-latest
    needs: run-npm-build
    steps:
      - uses: actions/checkout@v3
      - name: npm install and run test
        run: |
          npm install
          npm run test
