# .github/workflows/development.yml
name: Build and Deploy to Netlify
on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - main
      - development
jobs:
  run-test:
    name: "run test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: npm install and run test
        run: |
          npm install
          npm run test
