name: Deploy to heroku.

on:
  push:
    branches: [ main ]

jobs:
  build-artifacts:
    name: "Build Artifacts"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: npm install and build the Triplo website
        run: |
          npm install
          npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: Triplo
          path: './dist/apps/triplo'
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: './package.json'

  deploy:
    needs: build-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: Triplo
          path: './dist/apps/triplo'
      - name: Download artifact package
        uses: actions/download-artifact@v3
        with:
          name: Package
          path: './dist/apps/triplo/package.json'

      - name: Build, Push and Release a Docker container to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_directory: ./apps/api
          dockerfile_name: Dockerfile
          docker_options: "--no-cache"
          process_type: web
